AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway + Lambda + WAF + CloudFront with POST, CORS, and API Key support.

Parameters:
  LambdaSourceCodeS3Bucket:
    Type: String
    Description: S3 bucket for Lambda code.
  LambdaSourceCodeS3Key:
    Type: String
    Description: S3 key for Lambda zip file.

Resources:

  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:GetObject
                  - dynamodb:*
                Resource: "*"

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyApiHandler
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaSourceCodeS3Bucket
        S3Key: !Ref LambdaSourceCodeS3Key

  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MySecureApi

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt MyApi.RootResourceId
      PathPart: api

  ApiPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  ApiOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}/*/POST/api

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [ApiPostMethod, ApiOptionsMethod]
    Properties:
      RestApiId: !Ref MyApi
      StageName: prod

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: MyLocalClientApiKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref MyApi
          StageName: prod

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: MyUsagePlan
      ApiStages:
        - ApiId: !Ref MyApi
          Stage: prod
      Throttle:
        RateLimit: 10
        BurstLimit: 2
      Quota:
        Limit: 1000
        Period: MONTH

  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

  MyWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: MyApiWebACL
      Scope: CLOUDFRONT
      DefaultAction: { Allow: {} }
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: WAF
        SampledRequestsEnabled: true
      Rules:
        - Name: AWSCommon
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction: { None: {} }
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: Common
            SampledRequestsEnabled: true

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: api-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, POST, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: true
            Headers: ["Authorization", "X-Api-Key"]
        Origins:
          - Id: api-origin
            DomainName: !Sub "${MyApi}.execute-api.${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginPath: "/prod"
        WebACLId: !GetAtt MyWebACL.Arn

Outputs:
  ApiEndpoint:
    Description: Public API endpoint
    Value: !Sub "https://${MyCloudFrontDistribution.DomainName}/api"

  ApiKeyValue:
    Description: API Key for accessing the endpoint
    Value: !Ref ApiKey
